spring.application.name=MQTT

server.port:6060

#Mqtt Info
mqtt.publisherId = spring-server

mqtt.serverAddress =tcp://103.81.156.251:1883

# ask correct subscriberId
mqtt.subscriberId =tcp://103.81.156.251:1883

# Enable Code logging and Hibernate SQL logging
logging.level.com.onnet.mqtt=DEBUG

