/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.demo;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;
import com.example.demo.ExceptionHandling.NoSuchCommandException;
import com.example.demo.commands.CommandRegistry;

public class App {

    public static void main(String[] args) {
        if (args.length != 1){
            throw new RuntimeException();
        }
        List<String> commandLineArgs = new LinkedList<>(Arrays.asList(args));
        // run(commandLineArgs);
        commandLineArgs.add("INPUT-FILE=test_input_one.txt");
        String expectedSequence = "INPUT-FILE";
        String actualSequence = commandLineArgs.stream()
                .map(a -> a.split("=")[0])
                .collect(Collectors.joining(","));
        if(expectedSequence.equals(actualSequence)){
            run(commandLineArgs);
        }
    }

    public static void run(List<String> commandLineArgs){

        Configuration conf = Configuration.getInstance();

        CommandRegistry commandRegistry = conf.getCommandRegistry();
        
        String inputFile = commandLineArgs.get(0).split("=")[1];

        try(BufferedReader reader = new BufferedReader(new FileReader(inputFile))) {

            while (true) {
                String line = reader.readLine();
                if (line == null){
                    break;
                }
                commandRegistry.invokeCommand(line);
            }

        // } catch (Exception e) {
        //     e.printStackTrace();
        // }

        // BufferedReader bufferedReader;
        // String inputFile=commandLineArgs.get(0).split("=")[1];
        // commandLineArgs.remove(0);
        // try{
        //     bufferedReader=new BufferedReader(new FileReader(inputFile));
        //     String line= bufferedReader.readLine();
        //     while(line!=null){
        //         List<String> tokens=Arrays.asList(line.split(" "));
                
        //         System.out.println();
        //         line = bufferedReader.readLine();
        //         commandRegistry.invokeCommand(line);
        //     }
        //     bufferedReader.close();
        } catch (IOException  | NoSuchCommandException e) {
            e.printStackTrace();
        }
    }
}
