management.endpoints.web.exposure.include: '*'
server:
  port: 8080
logging:
  file:
    # path: /home/ltb/web/logs
spring:
  application.name: payment
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/airplane
    hikari.schema: localschema
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver 
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # Updated to MySQL 8 dialect
    show-sql: true
    hibernate:
      ddl-auto: update

paypal:
  clientId: AUrWd2yvnMBVfF3X3d_gCrVMK3kjKbNoV8tz0Rj5QNIglJVK-_ZLrVI3W5rEF19YJWbG_5Tq0CybSstK
  clientSecret: EDarqlbIjTzlRWvtViP5jSmAET4PRyWN-CF1e_xaxddTcFEAhGgazoRAWgVTaUkVrVMaSyaKZj3ViDKK